# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

filegroup(
    name = "spherical_injection_data",
    srcs = [
        "sv3d.bin",
        "video-sample-inject.mp4",
        "video-sample-inject_v1.mp4",
        "video-sample-inplace-inject.mp4",
        "video-sample_no_mesh.mp4",
    ],
)

filegroup(
    name = "replace_mett_with_camm_data",
    srcs = [
        "mett.mp4",
        "mett_replaced_with_camm.mp4",
    ],
)

filegroup(
    name = "edts_inject_data",
    srcs = [
        "edts_inject.mp4",
        "edts_misordered.mp4",
        "edts_missing.mp4",
        "edts_reorder.mp4",
    ],
)
